
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionUserService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/GestionUser/UserWS?wsdl")
public class GestionUserService
    extends Service
{

    private final static URL GESTIONUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONUSERSERVICE_EXCEPTION;
    private final static QName GESTIONUSERSERVICE_QNAME = new QName("http://service/", "GestionUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GestionUser/UserWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONUSERSERVICE_WSDL_LOCATION = url;
        GESTIONUSERSERVICE_EXCEPTION = e;
    }

    public GestionUserService() {
        super(__getWsdlLocation(), GESTIONUSERSERVICE_QNAME);
    }

    public GestionUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONUSERSERVICE_QNAME, features);
    }

    public GestionUserService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONUSERSERVICE_QNAME);
    }

    public GestionUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONUSERSERVICE_QNAME, features);
    }

    public GestionUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSPort")
    public UserWS getUserWSPort() {
        return super.getPort(new QName("http://service/", "UserWSPort"), UserWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSPort")
    public UserWS getUserWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "UserWSPort"), UserWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONUSERSERVICE_EXCEPTION!= null) {
            throw GESTIONUSERSERVICE_EXCEPTION;
        }
        return GESTIONUSERSERVICE_WSDL_LOCATION;
    }

}
